### ISSUE TITLE
Case is wrong for role in example playbook

### ISSUE THREAD

**Issue by nezda** [Comcast/ansible-sdkman#31]
https://github.com/Comcast/ansible-sdkman/blob/31473737d0e46858932b1386556cbda85478dbc6/README.md#L44

should be `role: comcast.sdkman`

**Comment by elliotweiser** [comment]
This is not strictly speaking true. For one thing, the GitHub organization name is `Comcast`, not `comcast`. Also the name that the role is given when it's downloaded is somewhat arbitrary. Though Ansible Galaxy specified `ansible-galaxy install comcast.sdkman` in the installation instructions, this is actually misleading. Both cases work when using `ansible-galaxy install`. Furthermore, downloading this role from a requirements file allows you to ultimately name it however you'd like:

```
name:
    Download the role to a specific name. Defaults to the Galaxy name when 
    downloading from Galaxy, otherwise it defaults to the name of the repository.
```

https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html
