### ISSUE TITLE
Test uses different role name `ansible-sdkman`

### ISSUE THREAD

**Issue by nezda** [Comcast/ansible-sdkman#32]
https://github.com/Comcast/ansible-sdkman/blob/31473737d0e46858932b1386556cbda85478dbc6/tests/test.yml#L5

should this be `comcast.sdkman`?

**Comment by elliotweiser** [comment]
No. The test uses the local name for the role because it shouldn't have to download it from Ansible galaxy. The tests should be able to run from the git repository.
