### ISSUE TITLE
https://sdkman.io/usage.html → https://sdkman.io/usage 

### ISSUE THREAD

**Issue by nezda** [Comcast/ansible-sdkman#33]
![image](https://user-images.githubusercontent.com/179091/49299242-e171eb80-f484-11e8-8149-aeffe321b3eb.png)

https://github.com/Comcast/ansible-sdkman/blob/31473737d0e46858932b1386556cbda85478dbc6/defaults/main.yml#L25

**Comment by elliotweiser** [comment]
Thanks for the head's up! I'll take care of that shortly.
