### ISSUE TITLE
libselinux-python had been renamed in recent RHEL

### ISSUE THREAD

**Issue by ghost** [Comcast/ansible-sdkman#54]
libselinux-python has been moved to python3-libselinux in Fedora 31, CentOS 8, etc. Currently the playbook fails because the package can't be found.

**Comment by elliotweiser** [comment]
Thanks for reporting this. I'll look into it when I can or will review PRs that address the issue.

**Comment by elliotweiser** [comment]
Sounds like it's also a good time to update https://github.com/Comcast/ansible-sdkman/blob/master/meta/main.yml#L15-L22 when the fix comes in.

**Comment by hermitmaster** [comment]
I’ll try to do a PR if I can find some time.

**Comment by danielporto** [comment]
I'm second to that. Just upgraded to centos8 and comcast.sdkman failed. :-/

**Comment by danielporto** [comment]
I've submitted a PR. Hope it fixes the problem.

**Comment by elliotweiser** [comment]
Closed in #58. Apologies for the delay. My hope is that, going forward, the CI challenges will have abated, enabling me to more easily to accept PRs.
